name: google_maps_webservice
description: Google Maps Web Services [API] (modernized for Dart 3 / http 1.x)
version: 0.0.20-modern.1
homepage: https://github.com/Anusxtt/google_maps_webservice

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  meta: ^1.11.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
  test: ^1.25.0
  coverage: ^1.10.0
